sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t qwseda123/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true qwseda123/docker-react npm run test -- --coverage
